/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bd81dc9974d26236b53a411c93a047b3)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	MACHINE_HOSTS: "api-staging.afixo.io" | "api.afixo.io";
	API: Fetcher /* afixo-api-staging */ | Fetcher /* afixo-api */;
}
declare namespace Cloudflare {
	interface StagingEnv {
		ASSETS: Fetcher;
		MACHINE_HOSTS: "api-staging.afixo.io";
		API: Fetcher /* afixo-api-staging */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MACHINE_HOSTS">> {}
}
